### ISSUE TITLE
how can i contact you

### ISSUE THREAD

**Issue by Tanasittx** [thisisawesome1994/youtube-video-bot#1]
i wanna talk something with you

**Comment by thisisawesome1994** [comment]
Why? You can talk on discord
Adoteq#2055

**Comment by Tanasittx** [comment]
request sent

**Comment by FreeYoutubeViews** [comment]
> i wanna talk something with you

The real bots and working are always paid not free so check me: http://dbtechlabs.com/ 
AND REMEMBER if someone gives a python file then why needs to load some youtubebot.exe  :D if there is selenium webdriver ?? hahahah a SIMPLE VIRUS possible a Miner Trojan :D

**Comment by FreeYoutubeViews** [comment]
> i wanna talk something with you


The real bots and working are always paid not free so check me: http://dbtechlabs.com/ 
AND REMEMBER if someone gives a python file then why needs to load some youtubebot.exe  :D if there is selenium webdriver ?? hahahah a SIMPLE VIRUS possible a Miner Trojan :D

**Comment by thisisawesome1994** [comment]
There is no such thing as a virus inside my bot programs.

That is why I upload the source-code aswell, so you can see IT for yourself...
